package net.sf.latexdraw.command.shape;

import io.github.interacto.jfx.test.UndoableCmdTest;
import java.util.List;
import java.util.stream.Stream;
import net.sf.latexdraw.model.ShapeFactory;
import net.sf.latexdraw.model.api.shape.ControlPointShape;
import net.sf.latexdraw.model.api.shape.Point;
import net.sf.latexdraw.service.PreferencesService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Test class for the command MoveCtrlPoint. Generated by Interacto test-gen.
 */
@Tag("command")
class MoveCtrlPointTest extends UndoableCmdTest<MoveCtrlPoint> {
	ControlPointShape shape;
	boolean isFirstCtrlPt;
	Point point;
	Point newCoord;
	Point memento;

	@BeforeEach
	void setUp() {
		bundle = new PreferencesService().getBundle();
	}

	@Override
	protected Stream<Runnable> canDoFixtures() {
		return Stream.of(() -> {
			fixtureShape();
			point = shape.getFirstCtrlPtAt(1);
			memento = ShapeFactory.INST.createPoint(point);
			isFirstCtrlPt = true;
			newCoord = ShapeFactory.INST.createPoint(20, -50);
			cmd = new MoveCtrlPoint(shape, point, isFirstCtrlPt);
			cmd.setNewCoord(newCoord);
		}, () -> {
			fixtureShape();
			point = shape.getSecondCtrlPtAt(1);
			memento = ShapeFactory.INST.createPoint(point);
			isFirstCtrlPt = false;
			newCoord = ShapeFactory.INST.createPoint(-100, 500);
			cmd = new MoveCtrlPoint(shape, point, isFirstCtrlPt);
			cmd.setNewCoord(newCoord);
		});
	}

	@Override
	protected Stream<Runnable> cannotDoFixtures() {
		return Stream.of(
			() -> cmd = new MoveCtrlPoint(ShapeFactory.INST.createBezierCurve(
				List.of(ShapeFactory.INST.createPoint())), ShapeFactory.INST.createPoint(1, 2), true),
			() -> cmd = new MoveCtrlPoint(ShapeFactory.INST.createBezierCurve(
				List.of(ShapeFactory.INST.createPoint())), ShapeFactory.INST.createPoint(1, 2), false),
			() -> {
			fixtureShape();
			point = shape.getFirstCtrlPtAt(1);
			cmd = new MoveCtrlPoint(shape, point, true);
			cmd.setNewCoord(ShapeFactory.INST.createPoint(10, Double.NaN));
		});
	}

	@Override
	protected Runnable doChecker() {
		return () -> {
			if(isFirstCtrlPt) {
				assertThat(shape.getFirstCtrlPts().get(1)).isEqualTo(ShapeFactory.INST.createPoint(20, -50));
			}else {
				assertThat(shape.getSecondCtrlPts().get(1)).isEqualTo(ShapeFactory.INST.createPoint(-100, 500));
			}
			assertThat(shape.isModified()).isTrue();
		};
	}

	private void fixtureShape() {
		shape = ShapeFactory.INST.createBezierCurve(List.of(
			ShapeFactory.INST.createPoint(),
			ShapeFactory.INST.createPoint(10, 23),
			ShapeFactory.INST.createPoint(45, 2)));
	}

	@Override
	protected Runnable undoChecker() {
		return () -> {
			assertThat(shape.isModified()).isFalse();
			if(isFirstCtrlPt) {
				assertThat(shape.getFirstCtrlPts().get(1)).isEqualTo(memento);
			}else {
				assertThat(shape.getSecondCtrlPts().get(1)).isEqualTo(memento);
			}
		};
	}
}
